#!/bin/bash

echo "Installing PatchApk v1.0"
echo "This Will Install The Following Tools"
echo "Ubuntu, ApkTool, Signapk And Java"
echo "Script Made By ng1nX4O4"
echo
sleep 3
echo
echo "Installing Required Packagess"
apt update &> /dev/null;
apt install wget unstable-repo gnupg -y &> /dev/null;
wget https://ng1nx4o4.github.io/termux-java/key.gpg &> /dev/null;
apt-key add key.gpg &> /dev/null;
echo "deb https://ng1nx4o4.github.io/termux-java termux extras" > $PREFIX/etc/apt/sources.list.d/java.list
apt update &> /dev/null;
echo "Installing Patch"
apt install msfpatch -y
echo "Installation Completed"
cd ~/PatchApk
mkdir decompiler
mkdir recompiler
mkdir final
mkdir payload
mkdir signed
mkdir unsigned
mkdir zipalign
mkdir script
cp patchapk $PREFIX/bin/.

termux-setup-storage

